
sudo: false

language: node_js
node_js:
    - "6.10"

cache:
    directories:
        - elm-stuff/build-artifacts/
        - elm-stuff/packages/
        - tests/elm-stuff/build-artifacts/
        - tests/elm-stuff/packages/

install:
    - npm -g install elm@'>=0.18 <0.19'
    - npm -g install elm-test@'>=0.18 <0.19'

script:
    - elm-test
